(define (lcs-length X Y)
  (let ((m (length X))
        (n (length Y)))
    (let ((c (make-array '#(0) `(-1 ,m) `(-1 ,n)))
          (b (make-array '#(#f) `(-1 ,m) `(-1 ,n))))
      (loop ((for i (up-from 0 (to m))))
            (loop ((for j (up-from 0 (to n))))
                  (if (eq? (list-ref X i) (list-ref Y j))
                      (begin
                        (array-set! c (+ (array-ref c (- i 1) (- j 1)) 1) i j)
                        (array-set! b '(-1 . -1) i j))
                      (let ((up (array-ref c (- i 1) j))
                            (left (array-ref c i (- j 1))))
                        (if (>= up left)
                            (begin
                              (array-set! c up i j)
                              (array-set! b '(-1 . 0) i j))
                            (begin
                              (array-set! c left i j)
                              (array-set! b '(0 . -1) i j)))))))
      (values c b))))

(define (lcs b X i j)
  (if (or (negative? i) (negative? j))
      '()
      (let ((displacement (array-ref b i j))
            (up-left? (lambda (displacement)
                        (equal? displacement '(-1 . -1)))))
        (let ((next (if (up-left? displacement)
                        (list (list-ref X i))
                        '())))
          (append (lcs b X (+ i (car displacement)) (+ j (cdr displacement)))
                  next)))))

(define (lcs/c c X Y)
  (define (iter l i j)
    (if (or (negative? i) (negative? j))
        l
        (let ((up (array-ref c (- i 1) j))
              (left (array-ref c i (- j 1)))
              (up-left (array-ref c (- i 1) (- j 1)))
              (this (array-ref c i j)))
          (if (equal? (list-ref X i) (list-ref Y j))
              (iter (cons (list-ref X i) l) (- i 1) (- j 1))
              (if (= this up)
                  (iter l (- i 1) j)
                  (iter l i (- j 1)))))))
  (iter '() (- (length X) 1) (- (length Y) 1)))
