(require-extension syntax-case check)
(require '../10.2/section)
(require '../11.1/section)
(require '../11.2/section)
(import section-10.2)
(import section-11.2)
(let ((table (make-ch-table 9 modulo-9-hash)))
  (let ((e5 (make-ch-element 5 (make-dlink 5 #f #f)))
        (e28 (make-ch-element 28 (make-dlink 28 #f #f)))
        (e19 (make-ch-element 19 (make-dlink 19 #f #f)))
        (e15 (make-ch-element 15 (make-dlink 15 #f #f)))
        (e20 (make-ch-element 20 (make-dlink 20 #f #f)))
        (e33 (make-ch-element 33 (make-dlink 33 #f #f)))
        (e12 (make-ch-element 12 (make-dlink 12 #f #f)))
        (e17 (make-ch-element 17 (make-dlink 17 #f #f)))
        (e10 (make-ch-element 10 (make-dlink 10 #f #f))))
    (ch-insert! table e5)
    (ch-insert! table e28)
    (ch-insert! table e19)
    (ch-insert! table e15)
    (ch-insert! table e20)
    (ch-insert! table e33)
    (ch-insert! table e12)
    (ch-insert! table e17)
    (ch-insert! table e10)
    (check (ch->vector table) =>
           '#(() (10 19 28) (20) (12) () (5) (33 15) () (17)))))
