(require-extension syntax-case check)
(require '../12.1/section)
(require '../12/chapter)
(import section-12.1)
(import chapter-12)
(let ((tree (make-bt-node #f '*root* #f #f #f)))
  (rt-insert! tree "0")
  (rt-insert! tree "011")
  (rt-insert! tree "10")
  (rt-insert! tree "100")
  (rt-insert! tree "1011")
  ;; Reverse lexicographic ordering an artifact of cons.
  (check (rt-preorder-tree-map bt-node-datum tree)
         => '("1011" "100" "10" "011" "0")))
