(require-extension syntax-case check)
(require '../12.1/section)
(require '../12.2/section)
(import section-12.1)
(import section-12.2)
(check (bt-node-datum (bt-min figure-12.2)) => 2)
(check (bt-node-datum (bt-max figure-12.2)) => 20)
