(require-extension syntax-case check (srfi 11))
(require '../16.1/section)
(import section-16.1)
(let* ((activities '((1 . 4)
                     (3 . 5)
                     (0 . 6)
                     (5 . 7)
                     (3 . 8)
                     (5 . 9)
                     (6 . 10)
                     (8 . 11)
                     (8 . 12)
                     (2 . 13)
                     (12 . 14))))
  (check (recursive-activity-selector activities) =>
         '((5 . 7) (8 . 11) (12 . 14))))
