(require-extension syntax-case check)
(require '../11.1/section)
(import section-11.1)
(let ((bit-vector 0))
  (set! bit-vector (bv-insert bit-vector 1))
  (set! bit-vector (bv-insert bit-vector 2))
  (set! bit-vector (bv-delete bit-vector 1))
  (check (bv-search bit-vector 2) => 2)
  (check (bv-search bit-vector 1) => #f))
