(require-extension syntax-case check)
(require '../12.1/section)
(require '../16.3/section)
(import section-12.1)
(import section-16.3)
(let ((frequencies (list (make-bt-node 5 "f" #f #f #f)
                         (make-bt-node 9 "e" #f #f #f)
                         (make-bt-node 12 "c" #f #f #f)
                         (make-bt-node 13 "b" #f #f #f)
                         (make-bt-node 16 "d" #f #f #f)
                         (make-bt-node 45 "a" #f #f #f))))
  (check (huffman-codes (huffman! frequencies)) =>
         '(((1 1 1) . "d") ((1 1 0 1) . "e") ((1 1 0 0) . "f")
           ((1 0 1) . "b") ((1 0 0) . "c") ((0) . "a"))))
