(require-extension syntax-case check)
(require '../16.3/section)
(import section-16.3)

(let* ((data '((4 . #f)
               (1 . #f)
               (3 . #f)
               (2 . #f)
               (16 . #f)
               (9 . #f)
               (10 . #f)
               (14 . #f)
               (8 . #f)
               (7 . #f)))
       (heap (make-heap car set-car! > +inf (length data) data)))
  (build-heap! heap)
  (check (heap-data heap) =>
         '((16 . #f) (14 . #f) (10 . #f) (8 . #f) (7 . #f) (9 . #f)
           (3 . #f) (2 . #f) (4 . #f) (1 . #f)))) 
