(require-extension syntax-case check)
(require '../12.1/section)
(require '../15.5/section)
(import section-12.1)
(import section-15.5)
(let ((root (list->array 2 '((0 0 1 1 1)
                             (0 1 1 1 3)
                             (0 0 2 3 4)
                             (0 0 0 3 4)
                             (0 0 0 0 4)))))
  (construct-optimal-bst root)
  (check (bt-preorder-tree-map bt-node-datum (make-optimal-bst root)) =>
         '("k1" "k4" "d4" "k3" "d3" "k2" "d2" "d1" "k0" "d0" "d-1")))
